apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rgha-secrets
  namespace: rgha
spec:
  provider: gke
  parameters:
    secrets: |
      # render.sh replaces PROJECT_ID.
      - resourceName: "projects/PROJECT_ID/secrets/rgha-github-app-key/versions/latest"
        path: "github-app.pem"
      - resourceName: "projects/PROJECT_ID/secrets/rgha-modal-toml/versions/latest"
        path: "modal.toml"
